# Entrega de Tareas

Para el curso se tienen:
- Retos de HackerRank
- Temas Relacionados con Tecnolgía
- Proyectos

## Formato de Entrega
* Para llevar registro de las tareas entregadas en HackerRank es necesario generar una cuenta en GitHub.
* Crear una carpeta ComputacionII.
* Agregar  las tareas en carpetas usando la clave que aparece en el listado de tareas descrito en este documento.
* Incluir en cada tarea:
  - CódigoFuente enviado a HackerRank.
  - Incluir el archivo capturaPantalla.png con la salida que muestra HackerRank al enviar.

## Trabajando con Github
- Crear una Cuenta en GitHub at https://github.com
  - Deberá ser una cuenta publica asociada con su nombre
  - Seleccione un usuario inteligentemente para su uso futuro.
  - No se preocupe sobre los detalles los puede llenar posteriormente.
- Crear un repositorio llamado de acuerdo a la clave de la tabla de tareas incluidas en este documento.

## Listado de Tareas
<table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Clave</th>
                    <th>Problema</th>
                    <th>Descripción</th>
                    <th>Fecha</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>hkr-1</td>
                    <td><p>2D Array - DS</p></td>
                    <td><p>Recorrer el patrón en las casillas del arreglo.</p></td>
                    <td>10/03/2017</td>
                </tr>
                <tr>
                    <td>2</td>
                    <td>hkr-2</td>
                    <td><p>CamelCase</p></td>
                    <td><p>&nbsp;Contar las palabras a partir de la regla de camelCase</p></td>
                    <td>10/03/2017</td>
                </tr>
                <tr>
                    <td>3</td>
                    <td>hkr-3</td>
                    <td><p>Sumatoria 2</p></td>
                    <td><p>&nbsp;Suma de las columnas de un arreglo o lista</p></td>
                    <td>10/03/2017</td>
                </tr>
                <tr>
                    <td>4</td>
                    <td>hkr-4</td>
                    <td><p>Caesar Cipher</p></td>
                    <td><p>&nbsp;Cifrador del Cesar</p></td>
                    <td>10/03/2017</td>
                </tr>
                <tr>
                    <td>5</td>
                    <td>hkr-5</td>
                    <td><p>The Power Sum</p></td>
                    <td><p>Suma de Potencias</p></td>
                    <td>10/03/2017</td>
                </tr>
                <tr>
                    <td>6</td>
                    <td>ti-1</td>
                    <td><p>Bootstrap, HTML5</p></td>
                    <td><p>Investigar sobre cómo Whatsapp, Snapchat y Tumblr generan ganancias.</p><p>Presentar en la plantilla de Boostrap que vimos en clase</p></td>
                    <td>24/02/2017</td>
                </tr>
                <tr>
                    <td>7</td>
                    <td>hkr-6</td>
                    <td><p>Clases y Objetos</p></td>
                    <td><p>Escribir la clase Point con los métodos descritos en HackerRank</p></td>
                    <td>27/03/2017</td>
                </tr>
            </tbody>
        </table>
